# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 15:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. 10 digits allowed.", regex='^\\d{10}$')])),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=10)),
                ('degree', models.CharField(choices=[('Bachelors of Technology', 'B-Tech'), ('Masters of Technology', 'mtech'), ('integerated dual degree', 'idd'), ('integerated masters degree', 'imd')], default=None, max_length=20)),
                ('department', models.CharField(choices=[('Computer Science and Engg.', 'cse'), ('Mathematics and Computing', 'mnc'), ('Electronics Engg.', 'ece'), ('Electrical Engg.', 'eee')], default=None, max_length=25)),
                ('sem', models.CharField(choices=[('I', '1'), ('II', '2'), ('III', '3'), ('IV', '4')], default=None, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
