# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='degree',
            field=models.CharField(choices=[('Bachelors of Technology', 'B-Tech'), ('Masters of Technology', 'mtech'), ('integerated dual degree', 'idd'), ('integerated masters degree', 'imd')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engg.', 'cse'), ('Mathematics and Computing', 'mnc'), ('Electronics Engg.', 'ece'), ('Electrical Engg.', 'eee')], default=None, max_length=55),
        ),
    ]
