# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('Deptt', models.CharField(choices=[('Computer Science & Engineering', 'cse'), ('Mathematics & Computing', 'mnc'), ('Electronics Engineering', 'ece'), ('Electrical Engineering', 'eee')], default=None, max_length=55)),
                ('sem', models.CharField(choices=[('I', '1'), ('II', '2'), ('III', '3'), ('IV', '4')], default=None, max_length=10)),
                ('Exam_Code', models.CharField(default=None, max_length=40)),
                ('ccode', models.CharField(choices=[('C1', '1'), ('C2', '2'), ('C3', '3'), ('C4', '4'), ('C5', '5'), ('C6', '6')], default=None, max_length=10)),
                ('scode', models.CharField(choices=[('Engg. Mech', '1'), ('Discrete Mathematics', '2'), ('Computer System Organisation', '3'), ('ITW', '4'), ('Probability & Statistics', '5'), ('Education & Self', '6')], default=None, max_length=50)),
            ],
        ),
    ]
